services:
  redis:
    image: redis:7-alpine
    command: redis-server /etc/redis.conf
    restart: unless-stopped
    ports:
        - 6379:6379
    volumes:
      - ./config/redis.conf:/etc/redis.conf
